### ISSUE TITLE
Add support for deploying to Open VSX Registry

### ISSUE THREAD

**Issue by michaeljolley** [clarkio/vscode-authentication-twitch#12]
Can we add a secret for the Open VSX Registry with the name `OVSX_PAT` adn then uncomment [this line](https://github.com/clarkio/vscode-authentication-twitch/blob/5991110601d5161eb85192ccb12322f0a9f5e324/.github/workflows/ci.yml#L150C46-L150C46) in the `.github/workflows/ci.yml` and `.github/workflows/manual-release.yml` files so that the package is installed to the OpenVSX registry?

This is needed by anyone (read: me) who has packages that rely on this extension who publishes to OpenVSX.

**Comment by clarkio** [comment]
Changes have been made and the CI pipeline is running here: https://github.com/clarkio/vscode-authentication-twitch/actions/runs/7433203552

**Comment by clarkio** [comment]
Done in #13
